# fly.toml app configuration file generated for spud-hub on 2025-05-24T00:07:34-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'spud-hub'
primary_region = 'sjc'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '4gb'
  cpu_kind = 'shared'
  cpus = 2
